# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03093bf59f760470f9f682f22a92db927a86d63d9c55bbff483f8c8593ea9bc23c5db7575189700904c0d29466b31e8dbe76b03d286b8e55e7f629e731644dfd

test:
  secret_key_base: 5856d8bbf9701c9aa68d8b4317ed4ec2f8b005ddd63b2c8a0cdc13398e163fcb430427350b1ca7251852aaa61383822cf399dd29f01e40f747480115b73637f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
